### ISSUE TITLE
gRPC RESOURCE_EXHAUSTED (quota exceeded) messages are not exposed to app

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [googleapis/nodejs-pubsub#1275]
_Originally posted by @mgabeler-lee-6rs in https://github.com/googleapis/nodejs-pubsub/issues/1135#issuecomment-828759419_:

Was perusing `GRPC_TRACE=all` logs to try to understand why a service was not receiving messages from PubSub, but also not receiving any error alerts from the library.

----

Monitoring the `all` traces, I happened to notice this fly by:
```
2021-04-28T20:22:44.751Z | call_stream | [157] Received server trailers:
                grpc-status: 8
                grpc-message: You have exceeded your StreamingPull connection quota (project="...elided..."). Refer to https://cloud.google.com/pubsub/quotas for more information.
```
And checking how many subs we've got in the project, and quota usage in GCP, I think this is the major problem we're hitting here.

Not being able to see this as an error or even a log at the application level is, IMO, frustrating at best. I think having `subscriber.on('error')` handlers get notified about this kind of issue (and any similar quota issues or other `RESOURCE_EXHAUSTED` type stuff) would be a good thing to add.

----

@murgatroid99 noted:
> Those errors really should be visible to the user. @feywind is PubSub transparently retrying RESOURCE_EXHAUSTED errors? If the server is sending errors like that the user needs to take action on, those errors really need to be exposed to the user.

----

@feywind confirmed it does: https://github.com/googleapis/nodejs-pubsub/issues/1135#issuecomment-829462457

**Comment by feywind** [comment]
Pinging on this to say that it's still on my radar and we're intending to fix it.

**Comment by feywind** [comment]
I've been looking into this a bit today. I think the likely (unfortunate) answer is that we can't do much here without a lot of work. I'm not entirely happy with that answer, so I've asked some people who work on gax if there's a way to get at that info, but basically:

1) We could remove RESOURCE_EXHAUSTED from the retryable list in the gapic config and then handle it at the client library layer; I think this is not really correct because gax is the right layer to handle transient errors (and I _think_ we generally do want to retry this and assume it's transient).

2) We could try to get a stream of advisory errors for things like this so you could log or flag it appropriately at the application layer; I think we can't do this right now because the retries happen in  a closed loop down in gax, and the only callback is for completion/failure.

**Comment by feywind** [comment]
@kamalaboulhosn Do you have any input on whether RESOURCE_EXHAUSTED should indeed be transient? Just double checking.

**Comment by feywind** [comment]
We talked this over a fair bit. The consensus seems to be that the behaviour of the current library is not ideal, but it's also not something that is happening very much across the board. So I'm going to put it in our backlog to improve this and expose the errors better, and close out the GH issue for now.

The simplest workaround is to turn on the GRPC debugging to see the error happening. That's not very satisfying, but it would at least give you some visibility for now (and you could set a log notification for that string).
