### ISSUE TITLE
When in a workflow should ack() and nack() be called?

### ISSUE THREAD

**Issue by Ezard** [googleapis/nodejs-pubsub#1477]
This is more of a general Pub/Sub question with some Node.js specifics; I couldn't find an answer anywhere in the GCP docs, but feel free to point me to them if I've just missed them :)

So I'm a little unsure how to use `ack()` and `nack()`:
I have a topic with a subscription, and that subscription is shared by a bunch of workers which all pull messages from it.
Each worker has some work to do, and at any point during that work, something could go wrong (e.g. something fata like process being killed, or something catch-able like a connection failure to the DB). In this case, I'd like the messages to be sent to another worker, essentially retrying until success. If possible, I'd also like this message to be prioritised over any other messages waiting to be processed (i.e. first-in-first-out).

Should I `ack` a message as soon as I receive it, and then try and call `nack` if something goes wrong? If the process dies then `nack` won't be called and the message disappears forever, so I'm unsure what should happen here.

Should I wait until the work is complete and then `ack` the message? There's variance in the amount of time a worker takes to do it's task, so to avoid the message being delivered to another worker should I just set `ackDeadlineSeconds` to a super high number and hope it's never exceeded? In this scenario would I `nack` the message if a non-fatal exception is caught, to trigger the retry?

Any guidance or pointers on how to handle this workflow would be very much appreciated, thanks!

**Comment by WesCossick** [comment]
@Ezard Since I've been doing a considerable amount of testing with the behavior of `.ack()` and `.nack()` lately, leading to the opening of #1482, I figured I'd try to answer your question based on my knowledge.

You should wait to call `.ack()` until the work on the message has successfully completed. If you call it before, and your code dies before it processes the message successfully, the message will not be re-delivered. I don't believe you can even call `.nack()` on a message after calling `.ack()` anyway, or at least I can't imagine it'd have any effect even if you could.

As far as making sure another subscriber ("worker") doesn't process the same message, there are a few solutions to this. You can do what you proposed, essentially setting the `ackDeadlineSeconds` to a high enough value that even messages with the longest processing times can complete in time.

Also, and this isn't very obvious, but you should know that by default this Node.js Pub/Sub client library automatically extends the acknowledge deadline for messages that haven't been ACK'd or NACK'd yet. By default, it'll keep extending the deadline for up to an hour, preventing the message from being delivered to any other subscriber during that time. You can customize how long it'll extend the deadline using `flowControl.maxExtensionMinutes`. Therefore, unless you customize the `maxExtensionMinutes`, the `ackDeadlineSeconds` isn't actually very meaningful. It's really the `maxExtensionMinutes` value that will determine when a message is re-attempted if it never gets ACK'd or NACK'd.

Another option to prevent two subscribers from processing the same message would be to use distributed locks (e.g., https://redis.io/topics/distlock).

You can also employ some combination of all three of these things, too. Robust production code would probably use locks at a minimum, since Pub/Sub only makes [an "at-least-once" delivery guarantee](https://cloud.google.com/pubsub/docs/subscriber#at-least-once-delivery).

All of this is caveated by the bug I described in #1482, which impacts how `.nack()` behaves and makes it somewhat risky (in my opinion) right now. Hopefully it gets fixed, though.

**Comment by Ezard** [comment]
Thanks for the detailed explanation @WesCossick!

I wasn't aware of `maxExtensionMinutes`, so that's super useful info to know. I think it could also explain an issue that pops up intermittently where all workers stop processing messages, without any errors appearing anywhere - each worker only pulls a single message at a time, so I assume that they all eventually ended with an unacked message which blocked anything else from happening (interestingly though, CPU usage of the workers increased massively during this period), at least until we restarted them all.

I'm not too bothered about the same message being processed by multiple workers since the work is idempotent, but that's still good info anyway, thanks

I'm unsure if your issue around `nack` would be an issue for us - we don't use exponential backoff, since if something went wrong then we usually want the message to be redelivered immediately, especially since PubSub will supposedly try and send the message to a different subscriber, which I _think_ would prevent the log jam that you're seeing (not 100% certain though, so definitely one for me to keep an eye on)

Thanks again!

**Comment by WesCossick** [comment]
Glad to help! By the way, whether you encounter a log jam due to #1482 would depend on whether retrying processing the message could fix the issue or not. If it's just a transient problem, say, a fluke network request failure, then a log jam won't happen. But if the message contains data that can't be processed (e.g., due to a bug), for which no amount of retrying will help, then that's when a log jam can occur.

Exponential backoff isn't really the cause; it's actually due to the fact that Pub/Sub immediately retries the same message whenever you call `.nack()`. So if you have as many messages calling `.nack()` as you have capacity to process simultaneously (number of subscribers multiplied by the number of messages per subscriber), you'll end up with a log jam. Basically, you'll end up retrying the message(s) that call `.nack()` over-and-over, and no other messages will be able to get through.

**Comment by feywind** [comment]
I brought this up at our team meeting today and it sounds like there might be some confusion about ack/nack semantics, so I just wanted to throw this out there to cap off:

- Calling nack() should cause the library to stop paying attention to a message, and will signal to the service that it can redeliver immediately

- As Wes said, don't call nack() after you've already called ack().

- All messages have no guarantee on which subscriber will receive it, so on nack(), it's possible that the same message may be redelivered immediately to the same subscriber, or to a different subscriber on the same topic. There's also no guarantee on the ordering of those individual messages. (I didn't think about asking how it applies to ordering keys, but it sounds like that's not in play here.)

- Once exactly-once subscription support drops for Node, you (@Ezard) might consider looking into that if you haven't found another solution. ack() and friends will have a return value that lets you know if your ack() was actually the one that was accepted for a message, or if one of your workers needs to roll back or something.
