### ISSUE TITLE
Please add sample for StreamingPull

### ISSUE THREAD

**Issue by RezaRahmati** [googleapis/nodejs-pubsub#1533]
Please add sample for StreamingPull

**Comment by feywind** [comment]
I linked this in another issue, but if anyone finds their way here, this is the golden path for streaming pull: https://github.com/googleapis/nodejs-pubsub/blob/main/samples/listenForMessages.js

**Comment by gitSambhal** [comment]
> I linked this in another issue, but if anyone finds their way here, this is the golden path for streaming pull: https://github.com/googleapis/nodejs-pubsub/blob/main/samples/listenForMessages.js

@feywind This example is not for streamingPull.

**Comment by feywind** [comment]
Streaming pull is the standard way the library pulls messages, and that sample is for the standard way -- the actual call to the streamingPull method is down in message-stream.ts:

https://github.com/googleapis/nodejs-pubsub/blob/main/src/message-stream.ts#L332

We don't have a sample for calling streamingPull() directly because it's not a recommended pattern for users (doing it properly is a lot of work).

**Comment by gitSambhal** [comment]
Thanks for the info @feywind
