### ISSUE TITLE
StreamingPullRequest is not exported in v1

### ISSUE THREAD

**Issue by RezaRahmati** [googleapis/nodejs-pubsub#1535]
#### Environment details

  - OS: Windows
  - Node.js version: 16
  - npm version: 8
  - `@google-cloud/pubsub` version: 2.19.0

#### Steps to reproduce

 trying to create an instance of StreamingPullRequest by these ways and seems it's not successful as it is not exported from v1

Attempt 1 
 ```
 const { v1 } = require('@google-cloud/pubsub');
 const request = new v1.StreamingPullRequest({subscription: 'sub'});
 ```

Attempt 2
```
 const { v1 } = require('@google-cloud/pubsub');
 const request = v1.StreamingPullRequest({subscription: 'sub'});
 ```

Attempt 3
```
 const { v1 } = require('@google-cloud/pubsub');
 const request = v1.StreamingPullRequest.create({subscription: 'sub'});
 ```

Thanks!

**Comment by feywind** [comment]
Echoing my comment on the other issue, this isn't really a code path we do much testing on, because the recommendation is to go through the library's streaming pull layer. That said, it looks like protos/protos.js contains the actual code definition you're looking for. I'm not too surprised if we're not exposing that explicitly, though.

@kamalaboulhosn Any thoughts on this one?

I'm curious what led you to use the raw API, because we're working on a V2 API right now, and if there's a shortcoming in the handwritten layer, I'd love to hear about that so we can incorporate it.

**Comment by kamalaboulhosn** [comment]
@feywind I would expect that someone could access this via the same place they would access, say, the unary pull method, which would be via the auto-generated library. Is that where this access is being done or is this an attempt to access via the hand-written layer on top of the auto-generated library?

**Comment by feywind** [comment]
@kamalaboulhosn This is accessing the auto-generated layer for streaming pull.

**Comment by feywind** [comment]
Mentioned in the other issue, but this is the streaming pull golden path: https://github.com/googleapis/nodejs-pubsub/blob/main/samples/listenForMessages.js

The streaming pull in v1 is possible to use, but it's really complicated to do properly, which is why the library has many layers on top of it.
