### ISSUE TITLE
Documentation missing from 2.18.2 onwards

### ISSUE THREAD

**Issue by bencon** [googleapis/nodejs-pubsub#1536]
All of a sudden in 2.18.2, Topic is missing a bunch of documentation sections. I don't think this was intentional, was it?
Compare
https://googleapis.dev/nodejs/pubsub/2.18.1/Topic.html
to
https://googleapis.dev/nodejs/pubsub/2.18.2/Topic.html

**Comment by feywind** [comment]
It looks like the new docs are going [here](https://cloud.google.com/nodejs/docs/reference/pubsub/latest). There are still some things that need improvement in there, like the ToC isn't organized per library, but you should be able to find everything in there.

Out of curiosity, where did you find the link to googleapis.dev? I want to start fixing those since the Cloud site is the new standard going forward.

**Comment by bencon** [comment]
There's a link to it here as "API Reference': https://cloud.google.com/nodejs/docs/reference/pubsub/latest

**Comment by feywind** [comment]
Okay, I get it now - that linked page is actually generated from the README.md, so that just needs to be updated.
