### ISSUE TITLE
Upgrade `google-gax` to 3.5.6 which doesn't include vulnerable `taffydb` package

### ISSUE THREAD

**Issue by tomgrossman** [googleapis/nodejs-pubsub#1692]
1) Is this a client library issue or a product issue?
library issue

#### Environment details

  - OS:
  - Node.js version: v18.12.1
  - npm version: 9.5.0
  - `@google-cloud/pubsub` version: 3.4.0

#### Steps to reproduce

  1. `npm i @google-cloud/pubsub@3.4.0`
  2. `npm list taffydb`:

![image](https://user-images.githubusercontent.com/6324938/223374490-416c4a86-5d25-4f35-afcc-19c66c35148c.png)

The `taffydb` has some [vulnerabilities](https://github.com/advisories/GHSA-mxhp-79qh-mcx6)

**Upgrading `google-gax` to `3.5.6` will resolve this issue since `taffydb` is not a sub-dependency of it.**

**Comment by feywind** [comment]
Thanks for the note. We talked about the taffydb issue a while back internally and decided that it wasn't a big priority since it's not actually used at runtime. If you want to make a PR that bumps the minimum up to gax `^3.5.6` I'll be happy to merge it, but since new installs will pull in the new version anyhow, I'm inclined to just wait for the next renovate-bot update.

**Comment by tomgrossman** [comment]
@feywind opened https://github.com/googleapis/nodejs-pubsub/pull/1694
