### ISSUE TITLE
High Latency (1800 msec) for message publish, create subscription, topic list, subscription list, create topic 

### ISSUE THREAD

**Issue by burningraven06** [googleapis/nodejs-pubsub#484]
Hello, 

I have initiated a pubsub client with the **@google-cloud/pubsub**  (version: 0.23.0)  npm package in my node app. Problem is, _any action I make_, ex: (List all topics, List all subscriptions, create topic etc) it takes around **2 secs (1800 ms )** to complete. 

Here, is a sample of my snippet.
Please let me know what seems to be the problem

```js
// Initialize App
const express = require('express')
const app = express()

// Initialize PubSub
const { PubSub }  = require("@google-cloud/pubsub");
const pubsubOpts = {
	projectId : process.env.PROJECT_ID, 
	keyFilename : path.join(__dirname, "keys/pubsubKey.json"),
	autoRetry : false,
	maxRetries : 5
}
const pubsub = new PubSub(pubsubOpts);


// List all Topics endpoint
app.get('/topics/list', async (req, res) => {
	try {
		const [topics] = await pubsub.getTopics();
		console.log('\nTopics :');
		topics.forEach(topic => console.log("Topic " , topic.name));
	} catch(err) {
		console.error("List Topic Err: ", err)
	}
	return res.status(200).json({ msg : "Check Console" })
})

// List All Subscriptions Endpoint
app.get("/subs/list", async (req, res) => {
	try {
		const [subscriptions] = await pubsub.getSubscriptions();
		console.log('\nSubscriptions:');
		subscriptions.forEach(subscription => console.log(subscription.name));
	} catch(err){
		console.error("\nList Subs Err: ", err)
	}
	return res.status(200).json({ msg : "Check Console"})
})

// Create Topic Endpoint
app.post('/topics/create', async (req, res) => {
	var topicName = req.body.topic
	try {
		await pubsub.createTopic(topicName);
		console.log("Topic ", topicName, " created.");
	} catch(err) {
		console.error("Topic Create Err : ", err)
	}
	return res.status(200).json({ msg : "Check Console"})
})

// Listen on port
app.listen(process.env.APP_PORT, () => console.log("Server Listening on ", process.env.APP_PORT))
```

Here are some screenshots from my Insomnia client. Any Function I try, it takes a massive amount of time to complete!

**List All Topics**
![topics_list](https://user-images.githubusercontent.com/18212542/52899738-8778fa80-3217-11e9-950d-a26c53a387ff.png)

**List All Subscriptions**
![subs_list](https://user-images.githubusercontent.com/18212542/52899744-9a8bca80-3217-11e9-9325-77601c37ed53.png)

**Create a Topic**
![topic_create](https://user-images.githubusercontent.com/18212542/52899746-a7102300-3217-11e9-84e0-2e39deccf9df.png)

I have also tried by removing **autoRetry : false, maxRetries : 5** from the pubsubOpts object but no luck. Please provide me a fix for this. Thanks.

**Comment by callmehiphop** [comment]
Hi @burningraven06 and thanks for the detailed writeup! Would you be able to provide us with some additional details about your environment?

* What OS are you running your application in?
* What version of Node are you using?
* Are you running your application in GCF, GKE, etc.?

**Comment by burningraven06** [comment]
Hi @callmehiphop, @yoshi-automation 

Sure I'd be glad to provide any info necessary.

1. I am using Ubuntu 18.04 (OS)
2. I am using Node v10.15.1 
3. I am running the app on my local machine

**Comment by callmehiphop** [comment]
@burningraven06 I've been messing around with your reproduction code and I was hoping you could spare a few more details with me.

1. How many Topics are returned via `pubsub.getTopics()`
1. How many Subscriptions are returned via `pubsub.getSubscriptions()`

My initial testing actually showed very similar latency, but it turned out I had quite a few lingering subscriptions and topics from various testing I've done previously. After I deleted the topics/subs associated with my project I saw significantly less latency

* `/topics/create`: 200ms~
* `/topics/list`: 100ms~
* `/subs/list`: 100ms~

This leads me to wonder how many pages of subscriptions and/or topics you might have. Both `getTopics` and `getSubscriptions` will make 1 request per page of resources you have, so in my case the latency came from requesting several pages worth of resources.

Of course this doesn't explain why it takes so long for your app to create a topic, I'm wondering if there could be any other outside factors contributing to the latency you're seeing.

**Comment by burningraven06** [comment]
HI, @callmehiphop 

Thanks for checking out my code.

I have 2 subscriptions.
I have 3 topics.

It's still taking around 2 seconds (1900 msec) for LIST (list topics,subs) operation.
For Creating a topic, it took nearly 7 seconds.

I'm not sure what else could be wrong, I ran it from another machine...

**Comment by callmehiphop** [comment]
Out of curiosity have you tried using Insomnia to hit the PubSub REST API directly? I'm curious what kind of latency you see from that.

**Comment by callmehiphop** [comment]
Haven't heard anything here in a while so I'm going to close this one out. If anyone experiences a similar issue or can provide new info, let us know! Thanks
