### ISSUE TITLE
Messages are not redelivered to subscriber.

### ISSUE THREAD

**Issue by MattGson** [googleapis/nodejs-pubsub#545]
#### Environment details

  - OS: OSX 10.11
  - Node.js version: 8
  - npm version: 4.6
  - `@google-cloud/pubsub` version: 0.26

#### Steps to reproduce

```
    const subscription = pubsub.subscription('subscription);

    const messageHandler = (message) => {

        _logger.info(`Message recieved: ${message.id}`);

        let data = JSON.parse(message.data);

        handleMessage(data).then(() => {
            message.ack();
            _logger.info(`Message ack: ${message.id}`);

        }).catch(err => {
            // message.nack();
            _logger.error(`Message not acked: ${message.id} `, err);
        });
    };

    subscription.on(`message`, messageHandler);
```

If an error is thrown then the message is not acked. At this point the message just sits in the queue forever. I have seen messages sit for several days. 

From the documentation, I believe a timeout should be reached and the message should be re-delivered. Currently, the only time the message is re-delivered is when the subscriber is restarted. Other messages continue to be processed normally. 

If I use message.nack(), the message is re-delivered immediately but this is not desired as cases such as DB failures can take time to resolve and I don't want it to retry continuously while this happens.

**Comment by callmehiphop** [comment]
@MattGson there is an option called `maxExtension` you can use to manage the duration of a message lock. By default it is set to `Infinity` which essentially translates to your subscriber uptime.

```js
const subscription = pubsub.subscription('my-sub', {
  flowControl: {maxExtension: 60 * 5} // 5 minutes
});
```

Hopefully this helps, if not, let us know!

**Comment by MattGson** [comment]
@callmehiphop Thanks, that has worked perfectly!

**Comment by MattGson** [comment]
So, the fix was short lived. Initially it worked with messages being redelivered after the maxExtension time and also upon restarting a subscriber. 

Now, the messages have started to build up in the queue again. This time, even restarting the subscriber is not triggering a redelivery.

The only thing that changed was that the original subscriber was run again a couple of times without the maxExtension option set.

One thing that confuses me is why this client has any responsibility for message redelivery? The cloud console subscriber page has an ack deadline option which looks like it is designed to control this behaviour? Can we not just use this configuration?

**Comment by callmehiphop** [comment]
@MattGson In regards to your messages not being delivered, do you know what the ack deadline is set to? Restarting the subscriber won't help here because it only manages messages it receives and there is no API for retrieving pending messages. If the deadline for the messages in question is set too far into the future then you'll have to either wait it out or manually modify the ack deadlines. 

> One thing that confuses me is why this client has any responsibility for message redelivery?

Our goal is to offer an easy to use interface that removes the need for some commonly needed features like batching and flow control.

> The cloud console subscriber page has an ack deadline option which looks like it is designed to control this behaviour? Can we not just use this configuration?

Absolutely you can, it is pretty easy to opt out of the message locking entirely, here's an example of what that would look like.

```js
const sub = pubsub.subscription('my-sub', {
  flowControl: {maxExtension: 0},
  ackDeadline: 5 * 60, // 5 minutes
});
```

One of the benefits in letting the client manage your messages is that there is a very low chance of an unwanted redelivery. You'll also see the redeliveries you want happen faster. If you lean on an ack deadline sometimes your messages might come much later, assuming you have a lengthy deadline.

**Comment by MattGson** [comment]
Ok, thanks for the information. The ack deadline for the subscription is set to the default value of 10 seconds so shouldn't be an issue? I'll play around with it and may end up disabling message locking as it is not really important in my application.

**Comment by ninjitaru** [comment]
thanks, didnt know about the lock
default ackDeadline is 10 second, should me reduce the lock below 10 second?

and reading the issue, i notice that we currently do not nack the message when we reach a recoverable error, i think we should to make sure so it can recover faster than ackdeadline time
