### ISSUE TITLE
message.ack() error handling impossible?

### ISSUE THREAD

**Issue by naugtur** [googleapis/nodejs-pubsub#575]
#### Environment details

  - OS: any
  - Node.js version: 10.x
  - npm version: 6.7
  - `@google-cloud/pubsub` version: 0.24.1

#### Issue details

We observed calling .ack() sometimes has no effect and the message is delivered again later.

Hypothesis: error in sending the ack.

https://github.com/googleapis/nodejs-pubsub/blob/3388fb735b87a8ac817c604cf777a5d8d4e7f833/src/subscriber.ts#L157
`message.ack()` is calling _subscriber.ack() which is async. Built version is wrapped with typescript magic based on generators that returns a promise, but message.ack is transpiled into a regular function so I'm assuming any errors within `subscriber.ack()` will get swallowed. Is that the case?

**Comment by callmehiphop** [comment]
@naugtur this is mostly true, we don't expose any errors from `message.ack()` although you can listen for any failures asynchronously like this

```js
subscription.on('error', err => console.error(err));
```

This will actually emit various errors relating to subscribing, however for ack failures a [`BatchError`](https://github.com/googleapis/nodejs-pubsub/blob/master/src/message-queues.ts#L49) is emitted with all the ack IDs that failed.

However it is worth noting that just because you see a redelivery, that doesn't necessarily mean that the acknowledge request failed. PubSub actually sends messages down in batches, my understanding is that if even 1 of those messages is not acknowledged they may redeliver the entire batch.

We've also been observing a bug (#468) where messages come DOA and PubSub lets us acknowledge them, but because the entire batch was expired they all end up getting redelivered.

**Comment by naugtur** [comment]
Error event is definitely helpful, will use.
I'll also look into deduplication in case of redelivery because what you wrote is quite scary.

**Comment by callmehiphop** [comment]
Yeah, it is kind of scary. Good news is that there is a new pure JavaScript gRPC library being written (currently we use a C++ addon) and we actually have the ability to tinker with flow control there. I've been seeing some pretty good results trying to lower the overall number of duplicates when testing with it, you might consider giving it a try. Although I will mention that it currently is still in beta, but so is the PubSub client. I believe you can enable it by setting the following environment variable

```sh
export GOOGLE_CLOUD_USE_GRPC_JS="1"
```

**Comment by callmehiphop** [comment]
@naugtur I'm going to close this, as I think I've answered your question? But please re-open or or create a new issue if you feel otherwise

**Comment by pworkpop** [comment]
Experiencing deadline exceeded errors with `@google-cloud/pubsub` 0.31.1
```
{ Error: Failed to "modifyAckDeadline" for 1 message(s). Reason: Retry total timeout exceeded before any response was received at Object.keys.map (/usr/src/app/node_modules/@google-cloud/pubsub/build/src/message-queues.js:201:23) ackIds: [ '...' ], code: 4, details: undefined, metadata: undefined }
{ Error: Failed to "acknowledge" for 1 message(s). Reason: Retry total timeout exceeded before any response was received at AckQueue._sendBatch (/usr/src/app/node_modules/@google-cloud/pubsub/build/src/message-queues.js:162:19) ackIds: [ '...' ], code: 4, details: undefined, metadata: undefined }
```

while these are delivered to the error handler on the subscription there is no possible way to retry that operation using the supplied ackIds without a reference to the message object? How are we supposed to handle such errors if `@google-cloud/pubsub` doesn't handle them?

**Comment by jcurlier** [comment]
+1
