### ISSUE TITLE
Need a sample that configures flow control settings with a subscriber client

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/nodejs-pubsub#669]
https://github.com/googleapis/nodejs-pubsub/blob/28400afd109429ff08e89a98ad73eeba061456b5/samples/subscriptions.js#L84

This sample shows how to configure a subscription with flow control settings. Please replace it with a new sample that shows how to configure flow control settings with a subscriber client. Samples in other languages can be found [here](https://cloud.google.com/pubsub/docs/pull#config).

**Comment by hongalex** [comment]
This is technically correct, but the issue lies in how the Node client library handles subscriptions and subscriber clients vs other languages. In Node, when `subscription` objects are instantiated, they also create a `subscriber` object and passes on its options. Thus while flow control settings are "configured" on the subscription, all its doing is passing down the options to the subscriber client that each subscription holds. Flow control settings on a subscription don't persist across different `subscription` object instantiations as indicated in the sample.

So the issue is now the fact that the API is slightly (even with the comment), since `subscription`s don't use the flow control settings at all, in the client library and in Pub/Sub.

@kamalaboulhosn @sduskis for FYI

**Comment by callmehiphop** [comment]
@hongalex currently there are no flow control settings available to Subscriber gapic. We have an internally used class called Subscriber which is not related to the gapic, I'm guessing this is where the confusion stems from. The Subscriber gapic client itself does not actually contain any flow control mechanisms, which is why we don't show a sample for it.

**Comment by hongalex** [comment]
Right. At the very least, I think the sample should be updated to clarify this. I want to highlight the fact that the subscription (which lives in Cloud Pub/Sub) is not being created with flow control settings, and that "client-side" subscription objects are not the same as the actual subscription resource in CPS.
