### ISSUE TITLE
doc: please describe`subscriberOptions`

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/nodejs-pubsub#684]
It's not super clear by referencing the documentation whether the options we set for [`topic.subscription(name[, options])`](https://googleapis.dev/nodejs/pubsub/latest/Topic.html#subscription) and [`pubsub.subscription(name[, options])`](https://googleapis.dev/nodejs/pubsub/latest/PubSub.html#subscription) are the same. 

- Are they both of `type SubscriberOptions`? But one just tells me it's of `type object`. 
- Why does `type SubscriberOptions` get a description that says "Subscription options"?  
- Is there a link we can add to `type SubscriberOptions`? Which values can users pass to it?

**Comment by callmehiphop** [comment]
There is a type we can link to, but I think because its [declared before a TypeScript interface](https://github.com/googleapis/nodejs-pubsub/blob/master/src/subscriber.ts#L193) it gets stripped out when compiled to JS. We need to move it somewhere else, probably above/below the Subscriber class overview docs.
