### ISSUE TITLE
Clarify potential misleading example

### ISSUE THREAD

**Issue by jakelowen** [googleapis/nodejs-pubsub#760]
**Is your feature request related to a problem? Please describe.**

I found the pubsub topic publish example very helpful: https://github.com/googleapis/nodejs-pubsub/blob/master/samples/topics.js#L84-L87

When I implemented a very similar publishMessage function in my code, I made what is now an obvious oversight, but one I probably would not have made with additional comments in the example.

In the publish message example the pubsub library is imported and instantiated inside the publish function. My naive interpretation is that creating a pubsub client via `const pubsub = new PubSub();` is a cheap enough operation such that it is ok to create a new client on each message publish. As such my code very much looked like the example. Predictably with hindsight I was opening too many pubsub clients and eventually encountering an "EMFILE" error. Moving the client instantiation out of the publishing function appears to have corrected the error as I monitor with `lsof | grep node | tail`

 **Describe the solution you'd like**

Maybe a comment in the examples that clarifies "Of course you would instantiate the client outside of any publish helper function"

**Comment by callmehiphop** [comment]
@jakelowen thanks for raising this issue! Everything you've said is totally reasonable to me, I believe the reason we do the require inside of the sample function is for completeness. 

@JustinBeckwith @bcoe thoughts here? I think this might be something we want to think about for all of our client library samples.

**Comment by bcoe** [comment]
@callmehiphop it would be worth bringing up with @fhinkel too ... I don't think we want to add a comment to every single sample, to the effect that you should only instantiate the client once.

At the same time, I totally agree that this can be confusing, and lead folks down the wrong path (especially for high throughput clients like PubSub).

**Comment by ctavan** [comment]
This issue is in fact even more intricate as there are also limitation as to how many parallel streams you can consume with one `PubSub` instance, see https://github.com/googleapis/nodejs-pubsub/issues/550#issuecomment-472778501 for reference.

So in some occasions it will be required to create multiple `PubSub` client instances, e.g. one for each subscription/topic (but definitely never one for every message).

What I want to highlight is that the conclusion is not to instantiate only _one_ `PubSub` client instance per process, but instead find a reasonable setup for each use case (I would suggest one per topic as a good rule of thumb that should prevent most problems in practice).

**Comment by fhinkel** [comment]
The code is wrapped in a function for testing purposes. The documentation that renders the sample doesn't show the function. IMO that makes it clear in the docs that the client doesn't need to be instantiated over and over again. 

I think the confusion comes from looking at GitHub instead of the docs. If we want to add a comment to the sample, it needs to be outside of what gets rendered in the docs.

**Comment by feywind** [comment]
I believe this was (mostly) taken care of in this PR: https://github.com/googleapis/nodejs-pubsub/pull/844

Basically when I reworked the samples into the latest style guide format, I also added comments suggestion that you should cache the PubSub object.
