### ISSUE TITLE
Broken flow control in rare cases

### ISSUE THREAD

**Issue by muryginm** [googleapis/nodejs-pubsub#80]
In production I have a memory consuming task. So if I get two messages at a time my app runs out of memory. I found out that flow control settings do not always works.

#### Environment details

  - OS: Ubuntu 16.04
  - Node.js version: 8.9.4
  - npm version: 5.5.1
  - @google-cloud/pubsub version: 0.16.4

I created a repository with code to reproduce this issue.

#### Steps to reproduce
  1. Clone repository https://github.com/muryginm/google-cloud-pubsub-issues
  2. `npm install`
  3. `GOOGLE_PROJECT=your-project-id GOOGLE_APPLICATION_CREDENTIALS=path-to-credentials npm run flow-control`
  4. Repeat step 3 a couple of times. At least one of 5 tests will fail.

In source code I created topic, subscription and track for messages that are currently in process. Am I doing something wrong?

Thanks!

**Comment by callmehiphop** [comment]
@muryginm based on some recent dialogue shared with me from the PubSub team, there is no guarantee that `maxMessages` will be hit exactly. That's because the PubSub API does not accept such an option and sometimes will give us batches of messages that can be higher than the desired limit.

As far as the increased memory usage, I've been chasing down similar reports (https://github.com/googleapis/nodejs-pubsub/issues/13) and hope to have a fix out soon.

I'm going to close this issue because I think the main issue being described is duplicative of another issue, but if you think this in incorrect, let me know and I'll be happy to re-open it.
