### ISSUE TITLE
document timeout configuration options in README

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-pubsub#810]
The user @oande was seeing errors in their log, due to `@google-cloud/pubsub` failing to find a message in the default timeout (see: #791).

Optimizing timeout settings helped the user reduce this category of error.

I think it would be good to add a section to our README that speaks to some of the tuning options that one might apply to `@google-cloud/pubsub` to help reduce noise in logs.

**Comment by bcoe** [comment]
@alexander-fenster or perhaps this is something we should configure in gax?

**Comment by meredithslota** [comment]
https://cloud.google.com/pubsub/docs/samples/pubsub-publisher-retry-settings#pubsub_publisher_retry_settings-nodejs and https://cloud.google.com/pubsub/docs/samples/pubsub-subscriber-flow-settings#pubsub_subscriber_flow_settings-nodejs offer some guidance on timeout configuration, for different uses. I'm inclined to close this since grpc-js has also evolved since that issue was filed and see if we encounter any newer issues. Please reopen if you think there's something we should do sooner. :)
